default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: space_crew_development

test:
  <<: *default
  database: space_crew_test

production:
  <<: *default
  database: space_crew_production
  username: space_crew
  password: <%= ENV["SPACE_CREW_DATABASE_PASSWORD"] %>
  